version: '3'
services:

  smtp:
    build: ./server
    image: res-smtp
    networks:
      default:
      smtp:

  mockmock:
    build: ./mockmock
    image: res-mockmock
    ports:
      - "8282:8282"
      - "2500:25"
    networks:
      default:
      smtp:

networks:
  smtp:
    driver: "bridge"
    name: smtp
