version: '3.5'
services:

  smtp:
    build: ./server
    image: res-smtp
    ports:
      - "2525:25"
    networks:
      default:
      smtp:
    labels:
    - "RES=SMTP"

  mockmock:
    build: ./mockmock
    image: res-mockmock
    ports:
      - "2500:25"
      - "8282:8282"
    networks:
      default:
      smtp:
    labels:
    - "RES=SMTP"

networks:
  smtp:
    driver: "bridge"
    name: smtp
